### ISSUE TITLE
@axiomhq/react does not work with vite getting Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Supcar27** [axiomhq/axiom-js#302]
I'm experiencing an issue with logging in my React client-side rendered app that uses Vite. The application fails to load and throws the following error:

```
Uncaught ReferenceError: process is not defined
```

This error occurs in the `platform.ts` file where Axiom is checking an environment variable using `process.env`.

#### Packages I'm using:
- "@axiomhq/js": "^1.3.1"
- "@axiomhq/logging": "^0.1.4"
- "@axiomhq/react": "^0.1.4"

#### Context
There is an open issue with Vite related to this problem [here](https://github.com/vitejs/vite/issues/1973). 

#### Temporary Solution
The only workaround that currently works in development is to add the following to the Vite configuration:

```javascript
  define: {
    "process.env": process.env,
  },
```

While this solution is functional in development, it does not address the underlying problem. 

#### Steps to Reproduce
1. Set up a React app using Vite.
2. Attempt to utilize Axiom for logging.
3. Observe the error when loading the application.

#### Expected Behavior
The app should load without errors related to `process.env`. 

Any insights or fixes would be greatly appreciated!

Thank you!

**Comment by thesollyz** [comment]
We have implemented a wrapper around those environment variables to safe guard the error, should work for your case. The new release is versioned `0.1.5`, let us know if all works out as expected 🙌

**Comment by thesollyz** [comment]
@peturgeorgievv our support would be happy to help you set things up or fix bugs. 
As for the ingest error, 403 means your token doesn't have the correct permissions, perhaps you selected a different dataset for that token permission and you are trying to ingest to a different dataset.

**Comment by peturgeorgievv** [comment]
@thesollyz nope, I created a fresh new dataset, created a token that is ingest for this specific dataset, and I get 403 from the React app. Not sure if localhost issue, but I tried even with proxy, and still the same.

I do use axiom for all my BE services and have custom dashboards for them, and it is quite nice, but the React library is pretty behind on everything for React, even though I appreciate the fact you're moving in that direction. The fact that even in the "docs" example there is a missing library that you need to install which is not a big deal, but means no one even tested what is written there.
